package org.example.Estados;

public enum Permiso {
    GESTION_USUARIOS,
    GESTION_PRODUCTOS,
    GESTION_CATEGORIA,
    GESTION_INVENTARIO,
    CONSULTAR_REPORTES,
    ADMINISTRAR_ORDENES,
    CONFIRMAR_PAGOS,
    GESTION_LOGISTICA
}
